export const email = [
    {
      id: "emailTemplates",
      title: "Email Templates",
      description: "Manage the templates for different types of emails sent from the system.",
      type: "select",
      options: ["Welcome Email", "Password Reset", "Course Enrollment", "Payment Confirmation", "Custom"],
      value: "Welcome Email", 
    },
    {
      id: "smtpConfiguration",
      title: "SMTP Configuration",
      description: "Set up the SMTP server for sending emails.",
      type: "group",
      fields: [
        {
          id: "smtpHost",
          title: "SMTP Host",
          description: "Enter the SMTP server host.",
          type: "text",
          value: "smtp.example.com", 
        },
        {
          id: "smtpPort",
          title: "SMTP Port",
          description: "Enter the SMTP server port.",
          type: "number",
          value: 587, 
        },
        {
          id: "smtpUsername",
          title: "SMTP Username",
          description: "Enter the SMTP server username.",
          type: "text",
          value: "user@example.com",
        },
        {
          id: "smtpPassword",
          title: "SMTP Password",
          description: "Enter the SMTP server password.",
          type: "text",
          value: "password123", 
        },
      ],
    },
    {
      id: "emailNotifications",
      title: "Email Notifications",
      description: "Enable or disable email notifications for different events.",
      type: "group",
      fields: [
        {
          id: "enableCourseEnrollmentEmail",
          title: "Course Enrollment Email",
          description: "Send email notifications when a user enrolls in a course.",
          type: "switch",
          value: true,
        },
        {
          id: "enablePasswordResetEmail",
          title: "Password Reset Email",
          description: "Send email notifications when a user requests a password reset.",
          type: "switch",
          value: true,
        },
        {
          id: "enablePaymentConfirmationEmail",
          title: "Payment Confirmation Email",
          description: "Send email notifications after a successful payment.",
          type: "switch",
          value: true, 
        },
      ],
    },
    {
      id: "defaultSenderEmail",
      title: "Default Sender Email",
      description: "Set the default email address from which emails will be sent.",
      type: "text",
      value: "noreply@example.com",
    },
    {
      id: "emailLogging",
      title: "Email Logging",
      description: "Enable or disable logging of email activities (e.g., sent emails, failed attempts).",
      type: "switch",
      value: false, 
    },
    {
      id: "emailTestMode",
      title: "Email Test Mode",
      description: "Enable email test mode to simulate email sending without actually sending emails.",
      type: "switch",
      value: false, 
    },
    {
      id: "emailQueue",
      title: "Email Queue",
      description: "Enable or disable email queuing for bulk email sending.",
      type: "switch",
      value: true, 
    },
  ];
  